### ISSUE TITLE
scipy.io.matlab.miobase.MatReadError: Mat file appears to be empty

### ISSUE THREAD

**Issue by trickyMan** [sergeyk/selective_search_ijcv_with_python#18]
**Hi, I encounter an issue, When I run selective_search.py , Here is the print.**
`[root@localhost selective_search_ijcv_with_python-master]# python selective_search.py 

Traceback (most recent call last):
  File "selective_search.py", line 62, in <module>
    boxes = get_windows(image_filenames)
  File "selective_search.py", line 41, in get_windows
    all_boxes = list(scipy.io.loadmat(output_filename)['all_boxes'][0])
  File "/usr/lib64/python2.7/site-packages/scipy/io/matlab/mio.py", line 134, in loadmat
    MR = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/usr/lib64/python2.7/site-packages/scipy/io/matlab/mio.py", line 58, in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)
  File "/usr/lib64/python2.7/site-packages/scipy/io/matlab/miobase.py", line 224, in get_matfile_version
    raise MatReadError("Mat file appears to be empty")
scipy.io.matlab.miobase.MatReadError: Mat file appears to be empty`

**And I noticed that the output .mat file is empty!!!
Also I checked the matlab script worked fine(Actually I don't know whether it's OK or not.):**

`[root@localhost selective_search_ijcv_with_python-master]# matlab -nojvm -r "try; selective_search({'/home/philip/Desktop/fast-rcnn/data/demo/selective_search_ijcv_with_python-master/000015.jpg','/home/philip/Desktop/fast-rcnn/data/demo/selective_search_ijcv_with_python-master/cat.jpg','/home/philip/Desktop/fast-rcnn/data/demo/selective_search_ijcv_with_python-master/000015.jpg','/home/philip/Desktop/fast-rcnn/data/demo/selective_search_ijcv_with_python-master/cat.jpg','/home/philip/Desktop/fast-rcnn/data/demo/selective_search_ijcv_with_python-master/000015.jpg','/home/philip/Desktop/fast-rcnn/data/demo/selective_search_ijcv_with_python-master/cat.jpg','/home/philip/Desktop/fast-rcnn/data/demo/selective_search_ijcv_with_python-master/000015.jpg','/home/philip/Desktop/fast-rcnn/data/demo/selective_search_ijcv_with_python-master/cat.jpg'}, '/tmp/tmpaRllSN.mat'); catch; exit; end; exit"

```
                                        < M A T L A B (R) >
                              Copyright 1984-2015 The MathWorks, Inc.
                               R2015b (8.6.0.267246) 64-bit (glnxa64)
                                          August 20, 2015
```

For online documentation, see http://www.mathworks.com/support
For product information, visit www.mathworks.com.
`

**My matlab verison is R2015b:**
`>> version
ans =
8.6.0.267246 (R2015b)
`
**My GCC version is:**
`[root@localhost fast-rcnn]# gcc --version
gcc (GCC) 6.2.1 20160916 (Red Hat 6.2.1-2)
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOS`

Please help!!!

**Comment by Lvhhhh** [comment]
i have the same problem and still not solved. please check the path of your picture and i have not seen mat produced by matlab
